# Setup
version_name: nyud
out_dir: "./exp_sel/"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 8
valBatch: 8
nworkers: 4
ignore_index: 255

# Optimizer and scheduler
val_interval: 5000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
lr_ts: True
scheduler: poly

# Model
model: TransformerMTL_multi
backbone: vitT
head: mlp

# Tasks
task_dictionary:
   include_loss_target_speed: True
   include_loss_checkpoint: True
   include_loss_semantic: True
   include_loss_bev_semantic: True
   include_loss_depth: True
   include_loss_bbox: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_weights:  
      loss_target_speed: 0.1
      loss_checkpoint: 0.1
      loss_semantic: 0.1
      loss_bev_semantic: 0.1
      loss_depth: 0.1
      loss_bbox: 0.1



loss_schema: affinity
group:
   group1:
    - loss_target_speed 
   group2:
    - loss_checkpoint
   group3:
    - loss_semantic
   group4:
    - loss_bev_semantic
   group5:
    - loss_depth
   group6:
    - loss_bbox

affin_decay: 0.001
preference: None
prepos: 10